SUBDIR = \
	hid \
	hidbus \
	hidmap \
	hidquirk \
	hidraw

SUBDIR += \
	bcm5974 \
	hconf \
	hidals \
	hcons \
	hgame \
	hkbd \
	hms \
	hmt \
	hpen \
	hsctrl \
	ietp \
	ps4dshock \
	u2f \
	xb360gp

.include <bsd.subdir.mk>
